---
certbot_install: true
certbot_install_source: apt

# https://eff-certbot.readthedocs.io/en/stable/using.html#dns-plugins
certbot_dns_plugin: cloudflare
certbot_dns_propagation_seconds: 30

certbot_domain: example.com
certbot_email: certbot@example.com

certbot_dir: /etc/letsencrypt
certbot_live_dir: "{{ certbot_dir }}/live/{{ certbot_domain }}"
certbot_archive_dir: "{{ certbot_dir }}/archive/{{ certbot_domain }}"
certbot_credentials: "{{ certbot_dir }}/credentials/{{ certbot_dns_plugin }}.ini"

# credentials
## https://certbot-dns-cloudflare.readthedocs.io/en/stable/
certbot_dns_cloudflare_api_token:

## https://certbot-dns-cloudxns.readthedocs.io/
certbot_dns_cloudxns_api_key:
certbot_dns_cloudxns_secret_key:

## https://certbot-dns-digitalocean.readthedocs.io/
certbot_dns_digitalocean_token:

## https://certbot-dns-linode.readthedocs.io/
certbot_dns_linode_key:
certbot_dns_linode_version:
