---
- name: install the prerequisites
  ansible.builtin.apt:
    name: "{{ nginx_apt_prerequisites }}"
    update_cache: true
    state: present

- name: ensure nginx_apt_repo_signed_by directory exists
  ansible.builtin.file:
    path: "{{ nginx_apt_repo_signed_by }}"
    state: directory

- name: import apt key
  ansible.builtin.get_url:
    url: "{{ nginx_apt_repo_spec[nginx_apt_repo].apt_key }}"
    dest: "{{ nginx_apt_repo_signed_by }}/{{ nginx_apt_repo }}.asc"
  when: nginx_apt_repo in ['nginx_org', 'xtom_com']

- name: add apt repo
  ansible.builtin.apt_repository:
    repo: "{{ nginx_apt_repo_spec[nginx_apt_repo].apt_repo }}"
    filename: "{{ nginx_apt_repo }}"
    state: present
  when: nginx_apt_repo in ['nginx_org', 'xtom_com']

- name: add apt pinning
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/99nginx
    content: "{{ nginx_apt_repo_spec[nginx_apt_repo].apt_pinning }}"
    mode: "0644"
  when: nginx_apt_repo in ['nginx_org', 'xtom_com']

- name: install nginx package
  ansible.builtin.apt:
    name: "{{ nginx_apt_repo_spec[nginx_apt_repo].apt_packages }}"
    update_cache: true
    state: present
