---
# (dynamic) include vars for debian
- include_vars: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

# tasks to apply changes
- include_tasks: debian-apply.yml
  when: nginx_state != 'absent' and ansible_facts['os_family']|lower == 'debian'

# tasks to revert most changes (not all, for security consideration)
- include_tasks: debian-revert.yml
  when: nginx_state == 'absent' and ansible_facts['os_family']|lower == 'debian'
