---
- name: install-docker playbook
  hosts: "{{ host | default('all') }}"

  roles:
    - role: common
      common_apt_repo_domain_ref: opentuna
      common_apt_force_ipv4: true

    - role: docker
      docker_apt_repo_ref: opentuna
      docker_apt_repo_channel: stable
      docker_daemon_registry_mirrors:
        - https://hub-mirror.c.163.com
        - https://mirror.baidubce.com
        - https://dockerproxy.com
