# ansible-playbook 02-install-certbot.yaml -e @credentials.yaml --ask-vault-pass --become
- name: install-certbot playbook
  hosts: "{{ host | default('all') }}"
  vars:
    domain:
      root: ak1ra.xyz
    certbot:
      plugin: cloudflare
      # place your cf_token with Zone.DNS permissions
      token: "{{ cf_token }}"

  roles:
  - role: common

  # certificate for nginx static server
  - role: certbot
    certbot_wildcard: true
    certbot_domain: "{{ domain.root }}"
    certbot_dns_plugin: "{{ certbot.plugin }}"
    certbot_dns_cloudflare_api_token: "{{ certbot.token }}"
    certbot_install: true
    certbot_install_source: apt
    certbot_cert_chmod: false
