---
- name: install-docker-certbot playbook
  hosts: "{{ host | default('all') }}"
  vars:
    domain:
      root: example.com
    certbot:
      plugin: cloudflare
      # place your cf_token with Zone.DNS permissions
      token: "{{ cf_token }}"

  roles:
    - role: common
      common_apt_repo_domain_ref: opentuna
      common_apt_force_ipv4: true

    - role: docker
      docker_apt_repo_ref: opentuna
      docker_apt_repo_channel: stable
      docker_daemon_registry_mirrors:
        - https://hub-mirror.c.163.com
        - https://mirror.baidubce.com
        - https://dockerproxy.com

    # certificate for nginx static server
    - role: certbot
      certbot_domain: "{{ domain.root }}"
      certbot_dns_plugin: "{{ certbot.plugin }}"
      certbot_dns_cloudflare_api_token: "{{ certbot.token }}"
      certbot_install: true
      certbot_install_source: apt
      certbot_cert_chmod: false
