---
# ansible-playbook 04-install-certbot-nginx.yaml -e @credentials.yaml --ask-vault-pass --become
- name: install-certbot-nginx playbook
  hosts: "{{ host | default('all') }}"
  vars:
    domain:
      root: ak1ra.xyz
      www: www.ak1ra.xyz
    certbot:
      plugin: cloudflare
      # place your cf_token with Zone.DNS permissions
      token: "{{ cf_token }}"

  roles:
    - role: common

    # certificate for nginx static server
    - role: certbot
      certbot_wildcard: true
      certbot_domain: "{{ domain.root }}"
      certbot_dns_plugin: "{{ certbot.plugin }}"
      certbot_dns_cloudflare_api_token: "{{ certbot.token }}"
      certbot_install: true
      certbot_install_source: apt
      certbot_cert_chmod: false

    - role: nginx
      nginx_apt_repo: debian

    # template base_config + server_config
    - role: nginx_config
      nginx_config_template_base_config: true
      nginx_config_template_server_config: true
      nginx_config_domain: "{{ domain.root }}"
      nginx_config_server_name: "{{ domain.www }}"
      nginx_config_server_type: static
