---
- name: install-v2ray playbook
  hosts: "{{ host | default('all') }}"
  vars:
    domain:
      root: example.com
      www: www.example.com
      # This will determine the location of v2ray_config_ssl_dir
      v2ray: srv.example.com
    certbot:
      plugin: cloudflare
      # place your cf_token with Zone.DNS permissions
      token: "{{ cf_token }}"
    v2ray:
      profile: vmess-wss
      uuid:

  roles:
    - role: common
      common_apt_repo_domain_ref: fastly
      common_apt_force_ipv4: true

    - role: docker

    # certificate for nginx static server
    - role: certbot
      certbot_domain: "{{ domain.root }}"
      certbot_dns_plugin: "{{ certbot.plugin }}"
      certbot_dns_cloudflare_api_token: "{{ certbot.token }}"
      certbot_install: true
      certbot_install_source: apt
      certbot_cert_chmod: false

    # certificate for v2ray vmess-wss profile
    - role: certbot
      certbot_domain: "{{ domain.v2ray }}"
      certbot_dns_plugin: "{{ certbot.plugin }}"
      certbot_dns_cloudflare_api_token: "{{ certbot.token }}"
      certbot_install: false
      # systemd DynamicUser need to be able to read privkey.pem
      certbot_cert_chmod: true

    - role: nginx
      nginx_apt_repo: nginx_org

    # template base_config + server_config
    - role: nginx_config
      nginx_config_template_base_config: true
      nginx_config_template_server_config: true
      nginx_config_domain: "{{ domain.root }}"
      nginx_config_server_name: "{{ domain.www }}"
      nginx_config_server_type: static

    - role: v2ray

    - role: v2ray_config
      v2ray_config_profile: "{{ v2ray.profile }}"
      v2ray_config_domain: "{{ domain.v2ray }}"
      v2ray_config_inbound_client_id: "{{ v2ray.uuid }}"
