---
# 此项为一些预先依赖
nginx_apt_prerequisites:
  - apt-transport-https
  - ca-certificates
  - curl
  - debian-archive-keyring
  - gnupg2
  - lsb-release

# 此项设置为 absent 可 revert 部分修改
# 如清理 apt key, apt repo, apt pinning 和所安装的 package
# 清理 nginx_apt_prerequisites 可能会破坏系统状态, 暂且不配置
# 如果已经执行过 roles/nginx 想切换另一个 packaging_team, 请先执行 revert ?
nginx_state: present

# nginx_apt_packaging_team 可以是: debian, nginx_org, xtom_com
# 此项设置为 debian 时, 表示不添加额外 apt repo 直接从官方源安装
nginx_apt_packaging_team: nginx_org

# debian 官方源只有 stable, xtom_com 只有 mainline
# nginx_org 同时提供 stable, mainline channel
nginx_apt_release_channel: mainline

# 如下为一些不常修改的静态配置
nginx_apt_release_channels:
  # https://nginx.org/en/linux_packages.html#Debian
  nginx_org:
    apt_key:
      url: https://nginx.org/keys/nginx_signing.key
      id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
    stable: "deb https://nginx.org/packages/debian {{ ansible_distribution_release }} nginx"
    mainline: "deb https://nginx.org/packages/mainline/debian {{ ansible_distribution_release }} nginx"
    pinning: |
      Package: *
      Pin: origin nginx.org
      Pin-Priority: 900
    packages:
      - nginx
      - nginx-common

  # https://n.wtf/install.html
  xtom_com:
    apt_key:
      url: https://n.wtf/public.key
      id: 1604614B4A6C2B73654BB8B6C5215CAF0055522F
    mainline: "deb https://mirror-cdn.xtom.com/sb/nginx/ {{ ansible_distribution_release }} main"
    pinning: |
      Package: *
      Pin: origin mirror-cdn.xtom.com
      Pin-Priority: 900
    packages:
      - nginx-extras
      - nginx-common
