---
nginx_apt_prerequisites:
  - apt-transport-https
  - ca-certificates
  - curl
  - debian-archive-keyring
  - gnupg2
  - lsb-release

# nginx_apt_packaging_team can be one of: debian, nginx.org, xtom.com
# when nginx_apt_packaging_team set to debian, install nginx from official debian apt repo
nginx_apt_packaging_team: nginx_org
nginx_apt_release_channel: mainline

nginx_apt_release_channels:
  # https://nginx.org/packages/debian/dists
  nginx_org:
    apt_key:
      url: https://nginx.org/keys/nginx_signing.key
      id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
      file: /usr/share/keyrings/nginx-archive-keyring.gpg
    stable: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] https://nginx.org/packages/debian {{ ansible_distribution_release }} nginx"
    mainline: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] https://nginx.org/packages/mainline/debian {{ ansible_distribution_release }} nginx"
    pinning: |
      Package: *
      Pin: origin nginx.org
      Pin-Priority: 900

  # NOTE: This repo only contain mainline channel
  # https://mirror-cdn.xtom.com/sb/nginx/dists/
  xtom_com:
    apt_key:
      url: https://n.wtf/public.key
      id: 1604614B4A6C2B73654BB8B6C5215CAF0055522F
      file: /usr/share/keyrings/n.wtf.asc
    mainline: "deb [signed-by=/usr/share/keyrings/n.wtf.asc] https://mirror-cdn.xtom.com/sb/nginx/ {{ ansible_distribution_release }} main"
    pinning: |
      Package: *
      Pin: origin mirror-cdn.xtom.com
      Pin-Priority: 900
