---
- name: ansible-galaxy collection install
  hosts: "{{ host | default('local') }}"
  tasks:
    - name: ansible-galaxy collection install
      environment:
        PATH: "{{ ansible_env['HOME'] }}/.local/bin:{{ ansible_env['PATH'] }}"
      community.general.ansible_galaxy_install:
        name: git+https://github.com/ak1ra-lab/selfhosted-server.git
        type: collection
        force: true

    - name: pipx inject required packages
      community.general.pipx:
        name: ansible
        state: inject
        inject_packages:
          - boto3
          - botocore
          - jmespath
