---
- name: ensure directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nginx_config_user }}"
    group: "{{ nginx_config_group }}"
    mode: "0755"
  loop:
    - /etc/nginx
    - /etc/nginx/conf.d
    - /var/log/nginx
    - /var/www

- include_tasks: base.yml
  when: nginx_config_copy_base

- include_vars: server.yml
  when: nginx_config_template_server

- include_tasks: server.yml
  when: nginx_config_template_server
