---
# fhs-install-v2ray.sh installed files
#   /usr/local/bin/v2ray
#   /usr/local/bin/v2ctl
#   /usr/local/share/v2ray/geoip.dat
#   /usr/local/share/v2ray/geosite.dat
#   /usr/local/etc/v2ray/config.json
#   /var/log/v2ray/access.log
#   /var/log/v2ray/error.log
#   /etc/systemd/system/v2ray.service
#   /etc/systemd/system/v2ray@.service

# common variables
v2ray_version:
