---
# v2ray_installed_files:
#   - /usr/local/bin/v2ray
#   - /usr/local/share/v2ray/geoip.dat
#   - /usr/local/share/v2ray/geosite.dat
#   - /usr/local/etc/v2ray/config.json
#   - /etc/systemd/system/v2ray.service
#   - /etc/systemd/system/v2ray@.service
#   - /var/log/v2ray

# common variables
v2ray_version: latest
v2ray_api_url: "https://api.github.com/repos/v2fly/v2ray-core/releases/{{ v2ray_version }}"

# v2ray user
v2ray_user: v2ray
v2ray_group: v2ray
v2ray_user_shell: /usr/sbin/nologin

# set_fact
v2ray_asset_name:
v2ray_asset_url:
v2ray_asset_checksum:
# md5, sha1, sha256, sha512
v2ray_asset_checksum_algo: sha512
# algorithm name in .dgst file has changed to SHA2-* for sha2 checksum (eg. sha256, sha512)
v2ray_asset_checksum_algo_prefix:
  md5: MD5
  sha1: SHA1
  sha256: SHA2-256
  sha512: SHA2-512

# file hierarchy inherited from https://github.com/v2fly/fhs-install-v2ray
v2ray_prefix: /usr/local
v2ray_bin_dir: "{{ v2ray_prefix }}/bin"
v2ray_dat_dir: "{{ v2ray_prefix }}/share/v2ray"
v2ray_etc_dir: "{{ v2ray_prefix }}/etc/v2ray"
v2ray_systemd_dir: /etc/systemd/system

# logs dir
v2ray_log_dir: "/var/log/v2ray"
