---
# 启用 https 需要安装 apt-transport-https
common_apt_repo_schema: https

# 此项设置为下方 common_apt_repo_domains 的任意一个 key
common_apt_repo_domain_ref: fastly
common_apt_repo_domains:
  fastly: deb.debian.org
  aliyun: mirrors.aliyun.com
  tencentcloud: mirrors.cloud.tencent.com
  ustc: mirrors.ustc.edu.cn
  tuna: mirrors.tuna.tsinghua.edu.cn
  hit: mirrors.hit.edu.cn
  sjtu: mirror.sjtu.edu.cn
  opentuna: opentuna.cn

common_apt_repo_url: "{{ common_apt_repo_schema }}://{{ common_apt_repo_domains[common_apt_repo_domain_ref] }}"

# 强制 apt 使用 IPv4
common_apt_force_ipv4: true

# 是否开启 TCP BBR 拥塞控制算法
common_set_tcp_bbr: false

# 是否设置 IPv4 ip_forward
common_set_ip_forward: false

# 是否设置自定义 sysctl.conf
common_set_custom_sysctl_conf: false

# 是否设置自定义 /etc/ssh/sshd_config
common_set_custom_sshd_config: true

common_apt_prerequisites:
  - apt-transport-https
  - ca-certificates
  - curl
  - debian-archive-keyring
  - gnupg2
  - lsb-release

common_apt_packages:
  - bash-completion
  - bc
  - binutils
  - bsdextrautils
  - bsd-mailx
  - build-essential
  - bzip2
  - cpio
  - cron
  - curl
  - dnsutils
  - dos2unix
  - file
  - fontconfig
  - gawk
  - git
  - gnupg2
  - htop
  - iftop
  - imagemagick
  - iotop
  - iperf3
  - iproute2
  - iputils-arping
  - iputils-clockdiff
  - iputils-ping
  - iputils-tracepath
  - jq
  - less
  - locales
  - logrotate
  - ncdu
  - ntp
  - p7zip
  - p7zip-full
  - parallel
  - parted
  - python3
  - python3-dev
  - python3-pip
  - python3-setuptools
  - python3-venv
  - rename
  - rsync
  - screen
  - stow
  - sudo
  - telnet
  - tmux
  - tree
  - unzip
  - vim
  - wget
  - xxd
  - xz-utils
  - zip
  - zlib1g
  - zlib1g-dev
