---
# str: 此项设置为下方 apt_repo_mirrors 的某个 key
apt_repo_key: debian
apt_repo_mirrors:
  debian: https://deb.debian.org
  aliyun: https://mirrors.aliyun.com
  tencent: https://mirrors.tencent.com
  ustc: https://mirrors.ustc.edu.cn
  tuna: https://mirrors.tuna.tsinghua.edu.cn
  hit: https://mirrors.hit.edu.cn
  sjtu: https://mirror.sjtu.edu.cn

# list[str]: Which types of packages to look for from a given source; either binary deb or source code deb-src.
apt_repo_types:
  - deb

# list[str]: debian repo suites
# https://deb.debian.org/debian/dists/
# bookworm, bookworm-updates, bookworm-backports
apt_repo_debian_suites:
  - "{{ ansible_distribution_release }}"
  - "{{ ansible_distribution_release }}-updates"
# list[str]: debian repo components
apt_repo_debian_components:
  - main
  - contrib
  - non-free
  - non-free-firmware

# list[str]: debian-security suites
# https://deb.debian.org/debian-security/dists/
# bullseye-security, bookworm-security
apt_repo_debian_security_suites:
  - "{{ ansible_distribution_release }}-security"
# list[str]: debian-security components
apt_repo_debian_security_components:
  - main
  - contrib
  - non-free
  - non-free-firmware

# bool: 是否启用 debian-backports
# 启用 debian-backports 会同时设置 linux kernel preferences 与自动更新来自 debian-backports 中的 packages, 可能存在副作用, 默认不启用
apt_repo_debian_suites_backports_enabled: false

# bool: 是否启用 ${distro_codename}-updates 自动更新
# 默认配置文件中 "origin=Debian,codename=${distro_codename}-updates"; 行被注释掉的
# 启用 ${distro_codename}-updates 同样存在潜在的副作用, 此处默认禁用
unattended_upgrade_updates_enabled: false

# bool: 是否允许 unattended-upgrades 更新后自动重启
unattended_upgrade_automatic_reboot_enabled: false
unattended_upgrade_automatic_reboot_time: "02:00"

# bool: 强制 apt 使用 IPv4
apt_force_ipv4_enabled: true

# bool: 是否开启 TCP BBR 拥塞控制算法
tcp_bbr_enabled: false

# bool: 是否设置 IPv4 ip_forward
ip_forward_enabled: false

# bool: 是否设置自定义 /etc/ssh/sshd_config
custom_sshd_config_enabled: true
custom_sshd_config_entries:
  ## Specifies whether root can log in using ssh(1).
  ## The argument must be yes, prohibit-password, forced-commands-only, or no. The default is prohibit-password.
  - regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin prohibit-password"
  ## Specifies whether password authentication is allowed. The default is yes.
  - regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
  ## Specifies whether TCP forwarding is permitted. The default is yes.
  ## vscode: remote.SSH extension makes use of an SSH tunnel to facilitate communication with the host.
  - regexp: "^#?AllowTcpForwarding"
    line: "AllowTcpForwarding yes"
  ## Specifies whether forwarding Unix domain sockets is permitted. The default is yes.
  ## vscode: `remote.SSH.remoteServerListenOnSocket` requires this to be yes.
  - regexp: "^#?AllowStreamLocalForwarding"
    line: "AllowStreamLocalForwarding yes"

# bool: 是否设置自定义 sysctl.conf
# 我并不完全理解下面这些值的作用, 因此此项默认值为 false
custom_sysctl_conf_enabled: false
custom_sysctl_conf_entries:
  # ref: https://www.kernel.org/doc/html/latest/admin-guide/sysctl/net.html
  # Low latency busy poll timeout for socket reads. (needs CONFIG_NET_RX_BUSY_POLL)
  - name: net.core.busy_read
    value: "50" # default 0 (off)

  # Low latency busy poll timeout for poll and select. (needs CONFIG_NET_RX_BUSY_POLL)
  - name: net.core.busy_poll
    value: "50" # default 0 (off)

  # The maximum send socket buffer size in bytes, hard limit.
  # default: not given in docs, but 212992 (208 KiB) in Debian 11
  - name: net.core.wmem_max
    value: 8388608

  # The maximum receive socket buffer size in bytes, hard limit.
  # default: not given in docs, but 212992 (208 KiB) in Debian 11
  - name: net.core.rmem_max
    value: 8388608

  # Maximum ancillary buffer size allowed per socket.
  # Ancillary data is a sequence of struct cmsghdr structures with appended data.
  # default: not given in docs, but 20480 in Debian 11
  - name: net.core.optmem_max
    value: 20480

  # Maximum number of packets, queued on the INPUT side,
  # when the interface receives packets faster than kernel can process them.
  # default: not given in docs, but 1000 in Debian 11
  - name: net.core.netdev_max_backlog
    value: 5000

  # ref: https://www.kernel.org/doc/html/latest/networking/ip-sysctl.html#tcp-variables
  # [min, default, max] receive buffer used by TCP sockets.
  # default: [4K, 128K, 128K ~ 6MB], max does not override net.core.rmem_max
  - name: net.ipv4.tcp_rmem
    value: 4096 131072 6291456

  # [min, default, max] amount of memory reserved for send buffers for TCP sockets.
  # default: [4K, 16K, 64K ~ 4MB], max does not override net.core.wmem_max
  - name: net.ipv4.tcp_wmem
    value: 4096 16384 4194304

  # Enable TCP Fast Open (RFC7413) to send and accept data in the opening SYN packet.
  # default: 0x1 (client), to enable both client and server support, set to 0x3.
  - name: net.ipv4.tcp_fastopen
    value: "3"

  # If set, provide RFC2861 behavior and time out the congestion window after an idle period.
  # An idle period is defined at the current RTO. If unset, the congestion window will not be timed out after an idle period.
  # default: 1
  - name: net.ipv4.tcp_slow_start_after_idle
    value: "0"

  # ref: https://www.kernel.org/doc/html/latest/admin-guide/sysctl/vm.html
  # Contains, as a percentage of total available memory that contains free pages and reclaimable pages,
  # the number of pages at which a process which is generating disk writes will itself start writing out dirty data.
  - name: vm.dirty_ratio
    value: "30"

  # Contains, as a percentage of total available memory that contains free pages and reclaimable pages,
  # the number of pages at which the background kernel flusher threads will start writing out dirty data.
  - name: vm.dirty_background_ratio
    value: "10"

  # This control is used to define the rough relative IO cost of swapping and filesystem paging, as a value between 0 and 200.
  # default: 60
  - name: vm.swappiness
    value: "30"

common_apt_packages:
  - bash-completion
  - bc
  - btop
  - bzip2
  - curl
  - dnsutils
  - dos2unix
  - file
  - gawk
  - git
  - gnupg2
  - htop
  - iftop
  - iotop
  - iperf3
  - jq
  - less
  - logrotate
  - mtr
  - ncdu
  - p7zip
  - p7zip-full
  - parallel
  - parted
  - pipx
  - python3
  - python3-pip
  - rename
  - rsync
  - screen
  - stow
  - systemd-cron
  - systemd-oomd
  - telnet
  - tmux
  - tree
  - unattended-upgrades
  - vim
  - xxd
