---
common_custom_sysctl_conf:
  # ref: https://www.kernel.org/doc/html/latest/admin-guide/sysctl/net.html
  # Low latency busy poll timeout for socket reads. (needs CONFIG_NET_RX_BUSY_POLL)
  - name: net.core.busy_read
    value: "50" # default 0 (off)

  # Low latency busy poll timeout for poll and select. (needs CONFIG_NET_RX_BUSY_POLL)
  - name: net.core.busy_poll
    value: "50" # default 0 (off)

  # The maximum send socket buffer size in bytes, hard limit.
  # default: not given in docs, but 212992 (208 KiB) in Debian 11
  - name: net.core.wmem_max
    value: 8388608

  # The maximum receive socket buffer size in bytes, hard limit.
  # default: not given in docs, but 212992 (208 KiB) in Debian 11
  - name: net.core.rmem_max
    value: 8388608

  # Maximum ancillary buffer size allowed per socket.
  # Ancillary data is a sequence of struct cmsghdr structures with appended data.
  # default: not given in docs, but 20480 in Debian 11
  - name: net.core.optmem_max
    value: 20480

  # Maximum number of packets, queued on the INPUT side,
  # when the interface receives packets faster than kernel can process them.
  # default: not given in docs, but 1000 in Debian 11
  - name: net.core.netdev_max_backlog
    value: 5000

  # ref: https://www.kernel.org/doc/html/latest/networking/ip-sysctl.html#tcp-variables
  # [min, default, max] receive buffer used by TCP sockets.
  # default: [4K, 128K, 128K ~ 6MB], max does not override net.core.rmem_max
  - name: net.ipv4.tcp_rmem
    value: 4096 131072 6291456

  # [min, default, max] amount of memory reserved for send buffers for TCP sockets.
  # default: [4K, 16K, 64K ~ 4MB], max does not override net.core.wmem_max
  - name: net.ipv4.tcp_wmem
    value: 4096 16384 4194304

  # Enable TCP Fast Open (RFC7413) to send and accept data in the opening SYN packet.
  # default: 0x1 (client), to enable both client and server support, set to 0x3.
  - name: net.ipv4.tcp_fastopen
    value: "3"

  # If set, provide RFC2861 behavior and time out the congestion window after an idle period.
  # An idle period is defined at the current RTO. If unset, the congestion window will not be timed out after an idle period.
  # default: 1
  - name: net.ipv4.tcp_slow_start_after_idle
    value: "0"

  # ref: https://www.kernel.org/doc/html/latest/admin-guide/sysctl/vm.html
  # Contains, as a percentage of total available memory that contains free pages and reclaimable pages,
  # the number of pages at which a process which is generating disk writes will itself start writing out dirty data.
  - name: vm.dirty_ratio
    value: "30"

  # Contains, as a percentage of total available memory that contains free pages and reclaimable pages,
  # the number of pages at which the background kernel flusher threads will start writing out dirty data.
  - name: vm.dirty_background_ratio
    value: "10"

  # This control is used to define the rough relative IO cost of swapping and filesystem paging, as a value between 0 and 200.
  # default: 60
  - name: vm.swappiness
    value: "30"
