---
docker_apt_repo_ref: docker
docker_apt_repo_urls:
  docker: https://download.docker.com
  aliyun: https://mirrors.aliyun.com/docker-ce
  tencentcloud: https://mirrors.cloud.tencent.com/docker-ce
  ustc: https://mirrors.ustc.edu.cn/docker-ce
  tuna: https://mirrors.tuna.tsinghua.edu.cn/docker-ce
  hit: https://mirrors.hit.edu.cn/docker-ce
  sjtu: https://mirror.sjtu.edu.cn/docker-ce
  opentuna: https://opentuna.cn/docker-ce

docker_apt_repo_url: "{{ docker_apt_repo_urls[docker_apt_repo_ref] }}"

# The channel to install from: nightly, test, stable
docker_apt_repo_channel: stable

# update import apt key task due to depreciation of apt-key
docker_apt_key: "{{ docker_repo_url }}/linux/debian/gpg"
docker_apt_key_signed_by: /etc/apt/keyrings

docker_apt_repo: "deb [signed-by={{ docker_apt_key_signed_by }}/docker-ce.asc] {{ docker_repo_url }}/linux/debian {{ ansible_distribution_release }} {{ docker_apt_repo_channel }}"

# docker daemon settings
docker_daemon_registry_mirrors: []
  # - https://hub-mirror.c.163.com
  # - https://mirror.baidubce.com
  # - https://dockerproxy.com

docker_daemon_enable_buildkit: true
