all:
  hosts:
    node01:
      ansible_host: 192.168.56.21
      ansible_user: vagrant
    node02:
      ansible_host: 192.168.56.22
      ansible_user: vagrant
    node03:
      ansible_host: 192.168.56.23
      ansible_user: vagrant

  children:
    nodes:
      hosts:
        node01:
        node02:
        node03:
