# 此项为一些预先依赖
nginx_apt_prerequisites:
- apt-transport-https
- ca-certificates
- curl
- debian-archive-keyring
- gnupg2
- lsb-release

# nginx_apt_repo 可以是: debian, nginx_org, xtom_com
# 此项设置为 debian 时, 表示不添加额外 apt repo 直接从官方源安装
# nginx 开发模式分为 stable 和 mainline 两个 release channel, 其中,
# debian 官方源只有 stable channel, xtom_com 只有 mainline channel
# nginx_org 同时提供了 stable 和 mainline channel, 不过这里只使用其 stable channel
nginx_apt_repo: debian

# see: https://stackoverflow.com/a/72548342
nginx_apt_repo_signed_by_dir: /etc/apt/keyrings

# 如下为一些不常修改的静态配置
nginx_apt_repo_spec:
  debian:
    apt_packages:
    - nginx
    - nginx-common

  # https://nginx.org/en/linux_packages.html#Debian
  nginx_org:
    apt_key: https://nginx.org/keys/nginx_signing.key
    # stable: https://nginx.org/packages/debian/
    # mainline: https://nginx.org/packages/mainline/debian/
    apt_repo: "deb [signed-by={{ nginx_apt_repo_signed_by_dir }}/{{ nginx_apt_repo }}.asc] https://nginx.org/packages/debian {{ ansible_distribution_release }} nginx"
    apt_pinning: |
      Package: nginx
      Pin: origin nginx.org
      Pin-Priority: 900
    apt_packages:
    # 这个 repo 中的 nginx 没有拆开, 只有一个名为 nginx 的 package
    - nginx

  # https://n.wtf/install.html
  xtom_com:
    apt_key: https://n.wtf/public.key
    apt_repo: "deb [signed-by={{ nginx_apt_repo_signed_by_dir }}/{{ nginx_apt_repo }}.asc] https://mirror-cdn.xtom.com/sb/nginx/ {{ ansible_distribution_release }} main"
    apt_pinning: |
      Package: nginx-*
      Pin: origin mirror-cdn.xtom.com
      Pin-Priority: 900
    apt_packages:
    # 这个 repo 中的 nginx 有被拆开为多个 package, 其中 nginx-common 为一些配置文件
    - nginx
    - nginx-common
