---
- name: import facts
  ansible.builtin.import_tasks: facts.yml

- name: ensure cloud-init config
  ansible.builtin.import_tasks: cloud-init.yml

- name: ensure netpaln config
  ansible.builtin.import_tasks: netplan.yml

- name: ensure systemd-resolved config
  ansible.builtin.import_tasks: resolved.yml
