---
- name: ensure packages installed
  ansible.builtin.package:
    name:
      - netplan.io
    state: present

- name: create drop-in directory
  ansible.builtin.file:
    path: /etc/netplan
    mode: "0700"
    state: directory

# 执行过一次后 50-cloud-init.yaml 无论如何都会被重写
- name: manage netplan configuration
  vars:
    netplan_default: /etc/netplan/90-default.yaml
    netplan_cloud_init: /etc/netplan/50-cloud-init.yaml
    netplan_dest: "{{ netplan_default if not (cloud_init_network_config | ansible.builtin.bool) else netplan_cloud_init }}"
    netplan_remove: "{{ netplan_default if (cloud_init_network_config | ansible.builtin.bool) else netplan_cloud_init }}"
  block:
    - name: "template {{ netplan_dest }}"
      ansible.builtin.template:
        src: etc/netplan/90-default.yaml.j2
        dest: "{{ netplan_dest }}"
        mode: "0600"
      notify:
        - netplan apply
        - resolvectl flush-caches

    - name: "remove {{ netplan_remove }}"
      ansible.builtin.file:
        path: "{{ netplan_remove }}"
        state: absent
      notify:
        - netplan apply
        - resolvectl flush-caches
