---
- name: download tarball from HTTP
  ansible.builtin.get_url:
    url: "{{ deploy_tarball_url }}"
    dest: "{{ deploy_tarball_tempdir.path }}"
    owner: "{{ deploy_tarball_user }}"
    group: "{{ deploy_tarball_group }}"
  register: deploy_tarball_get_url_return

- name: decompress tarball downloaded from HTTP
  ansible.builtin.unarchive:
    src: "{{ deploy_tarball_get_url_return.dest }}"
    dest: "{{ deploy_tarball_dest }}"
    owner: "{{ deploy_tarball_user }}"
    group: "{{ deploy_tarball_group }}"
    remote_src: true
