---
# tasks file for roles/deploy_tarball
- name: check vars
  ansible.builtin.assert:
    that:
      - deploy_tarball_url is defined

- name: ensure deploy_tarball_group exists
  ansible.builtin.group:
    name: "{{ deploy_tarball_group }}"
    state: present

- name: ensure deploy_tarball_user exists
  ansible.builtin.user:
    name: "{{ deploy_tarball_user }}"
    group: "{{ deploy_tarball_group }}"
    home: "{{ deploy_tarball_user_home }}"
    shell: "{{ deploy_tarball_shell }}"
    state: present

- name: ensure directory exists
  ansible.builtin.file:
    path: "{{ deploy_tarball_dest }}"
    owner: "{{ deploy_tarball_user }}"
    group: "{{ deploy_tarball_group }}"
    mode: "0755"
    state: directory

- name: mktemp deploy_tarball_tempdir
  ansible.builtin.tempfile:
    state: directory
  register: deploy_tarball_tempdir

- name: include_tasks aws.yml if deploy_tarball_url in s3:// format
  when: deploy_tarball_url is ansible.builtin.regex('^s3://[a-z0-9\\.-]{3,63}/')
  ansible.builtin.include_tasks: aws.yml

- name: include_tasks http.yml if deploy_tarball_url in https?:// format
  when: deploy_tarball_url is ansible.builtin.regex('https?://')
  ansible.builtin.include_tasks: http.yml

- name: remove deploy_tarball_tempdir
  ansible.builtin.file:
    path: "{{ deploy_tarball_tempdir.path }}"
    state: absent
