- name: template /etc/nginx/nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify:
  - test new nginx config
  - reload nginx config

- name: copy nginx base config
  ansible.builtin.copy:
    # if it does not end with "/", the directory itself with all contents is copied.
    src: nginx
    dest: /etc/
    mode: preserve
  notify:
  - test new nginx config
  - reload nginx config
