---
- name: backup nginx config files
  community.general.archive:
    path: /etc/nginx
    dest: "/etc/nginx.{{ ansible_date_time.iso8601_basic_short }}.tgz"
    mode: "0644"
    remove: true

- name: check /etc/nginx/dhparam.pem
  ansible.builtin.stat:
    path: /etc/nginx/dhparam.pem
  register: stat_dhpram

- name: create /etc/nginx/dhparam.pem for later use
  ansible.builtin.command: openssl dhparam -out /etc/nginx/dhparam.pem 2048
  when: not stat_dhpram.stat.exists

- name: template /etc/nginx/nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"

- name: copy nginx base config
  ansible.builtin.copy:
    # if it does not end with "/", the directory itself with all contents is copied.
    src: nginx
    dest: /etc/
    mode: preserve
  notify:
    - test new nginx config
    - reload nginx config
