---
- name: ensure singbox_apt_key_signed_by directory exists
  ansible.builtin.file:
    path: "{{ singbox_apt_key_signed_by | dirname }}"
    state: directory

- name: import apt key
  ansible.builtin.get_url:
    url: "{{ singbox_apt_key }}"
    dest: "{{ singbox_apt_key_signed_by }}"

- name: add apt repo
  ansible.builtin.apt_repository:
    repo: "{{ singbox_apt_repo }}"
    filename: sagernet
    state: present

- name: add apt pinning
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/99sagernet
    content: |
      Package: *
      Pin: origin deb.sagernet.org
      Pin-Priority: 900
    mode: "0644"

# install sing-box or sing-box-beta
- name: install sing-box packages
  ansible.builtin.apt:
    name:
      - sing-box
    update_cache: true
    state: present
