---
# set_fact if curtain vars is not given
- name: include_tasks fact.yml
  ansible.builtin.include_tasks: fact.yml

- name: ensure directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    # We need to create v2ray_config_log_dir, Even though we are use
    # DynamicUser=yes with logsDirectory, otherwise the 'test v2ray config' will fail
    - "{{ v2ray_config_log_dir }}"
    - "{{ v2ray_config_etc_dir }}/{{ v2ray_config_type }}"
    - "{{ v2ray_config_dat_dir }}"

- name: template systemd service unit override
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ v2ray_config_systemd_dir }}/v2ray.service.d/{{ item | splitext | first }}"
    mode: "0644"
  loop:
    - 20-dynamic-user.conf.j2
  notify:
    - systemctl daemon-reload

- name: template client config
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ v2ray_config_etc_dir }}/{{ item | splitext | first }}"
    mode: "0644"
  loop:
    - client/00-log.json.j2
    - client/03-routing.json.j2
    - client/05-inbounds.json.j2
    - "client/06-outbounds-{{ v2ray_config_profile }}.json.j2"
  notify:
    - test v2ray config
    - restart v2ray service
  when: v2ray_config_type == "client"

- name: template server config
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ v2ray_config_etc_dir }}/{{ item | splitext | first }}"
    mode: "0644"
  loop:
    - server/00-log.json.j2
    - server/03-routing.json.j2
    - "server/05-inbounds-{{ v2ray_config_profile }}.json.j2"
    - server/06-outbounds.json.j2
  notify:
    - test v2ray config
    - restart v2ray service
  when: v2ray_config_type == "server"

- name: ensure v2ray service is started and enabled
  ansible.builtin.service:
    name: v2ray
    state: started
    enabled: true
