---
# tasks to apply changes
- name: install certbot
  ansible.builtin.include_tasks: install.yml
  when: certbot_install

- name: ensure certbot credentials dir exist
  ansible.builtin.file:
    path: "{{ certbot_credentials | dirname }}"
    state: directory
    mode: "0700"

- name: template certbot dns plugin credentials
  ansible.builtin.template:
    src: "{{ certbot_dns_plugin }}.ini.j2"
    dest: "{{ certbot_credentials }}"
    mode: "0600"

- name: execute certbot with dns plugin options
  ansible.builtin.command:
    argv:
      - certbot
      - certonly
      - --non-interactive
      - --agree-tos
      - "--email={{ certbot_email }}"
      - "--domain={{ certbot_domain }}"
      - "--dns-{{ certbot_dns_plugin }}"
      - "--dns-{{ certbot_dns_plugin }}-credentials={{ certbot_credentials }}"
      - "--dns-{{ certbot_dns_plugin }}-propagation-seconds={{ certbot_dns_propagation_seconds }}"
    creates:
      # If a matching file already exists, this step *will not* be run.
      - "{{ certbot_dir }}/live/{{ certbot_domain }}/privkey.pem"
