---
- name: ensure apt directories exists
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
  loop:
    - "/etc/apt/apt.conf.d"
    - "/etc/apt/keyrings"
    - "/etc/apt/preferences.d"
  loop_control:
    loop_var: directory

- name: import apt key
  ansible.builtin.get_url:
    url: "{{ jenkins_apt_key }}"
    dest: "{{ jenkins_apt_key_signed_by }}"

- name: add apt repo
  ansible.builtin.apt_repository:
    repo: "{{ jenkins_apt_repo }}"
    filename: jenkins-io
    state: present

- name: add apt pinning
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/90jenkins-io
    content: |
      Package: jenkins
      Pin: origin pkg.jenkins.io
      Pin-Priority: 900
    mode: "0644"

- name: add unattended-upgrade origin pattern
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/90unattended-upgrades-jenkins-io
    content: |
      Unattended-Upgrade::Origins-Pattern:: "origin=pkg.jenkins.io/debian-stable";
    mode: "0644"

- name: install jenkins packages
  ansible.builtin.apt:
    name:
      - fontconfig
      - openjdk-17-jre-headless
      - jenkins
    update_cache: true
    state: present
