---
# roles/apt_install

# https://learn.microsoft.com/en-us/linux/packages
apt_repo: microsoft

# https://packages.microsoft.com/debian/12/prod/
# 尽量避免使用 ansible_lsb, 它依赖 lsb_release, 在一些精简系统中可能缺失相关字段
apt_repo_uris: "https://packages.microsoft.com/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/prod"
apt_repo_suites: "{{ ansible_distribution_release }}"
apt_repo_components: main

# https://packages.microsoft.com/keys/README
# microsoft.asc (BC528686B50D79E339D3721CEB3E94ADBE1229CF):
# This key was Microsoft’s standard Linux-signing key until Spring 2025, as discussed above. This key will not be used for newly-created repositories.
# microsoft-2025.asc (AA86F75E427A19DD33346403EE4D7792F748182B):
# This is the current standard Linux-signing key that will be used in newly-created repositories. It will work properly in distributions that disallow SHA1 signatures.
# curl -s https://packages.microsoft.com/keys/microsoft.asc | gpg
# pub   rsa2048 2015-10-28 [SC]
#       BC528686B50D79E339D3721CEB3E94ADBE1229CF
# uid           Microsoft (Release signing) <gpgsecurity@microsoft.com>
# TODO: 2025-06-30 目前暂未切换至 microsoft-2025.asc
apt_key_url: https://packages.microsoft.com/keys/microsoft.asc

# **注意**:
# /etc/apt/keyrings 目录中, .gpg 对应 binary format, .asc 对应 ascii format, 二者不可混用, 否则 apt update 时会报错
# 有些 apt_key_url 提供的 key file 以 .gpg 结尾, 但实际上是 ascii format,
# 这种情况下设定 apt_keyrings_dest 时 key file 文件名需要使用 .asc 后缀, 反之亦然
apt_keyrings_dest: /etc/apt/keyrings/microsoft.asc

# https://manpages.debian.org/bookworm/apt/apt_preferences.5.en.html
apt_pinning: true
# A note of caution: the keyword used here is "origin" which can be used to match a hostname.
# This **should not be confused with** the Origin of a distribution as specified in a Release file.
# Pin 这一行的 origin 和 release 都是 keyword, 注意不要把 origin 与 release 中的 o=xxx 混淆, 后者来自 Release 或 InRelease 文件
# the Origin: line, names the originator of the packages in the directory tree of the Release file. Most commonly, this is Debian.
# All of the Packages and Release files retrieved from locations listed in the sources.list(5) file are stored in the directory /var/lib/apt/lists
apt_pinning_origin: "{{ apt_repo_uris | ansible.builtin.urlsplit('hostname') }}"

# https://wiki.debian.org/UnattendedUpgrades
apt_unattended_upgrades: true
# /etc/apt/apt.conf.d/50unattended-upgrades 中出现了 site keyword 可以用于匹配 hostname
apt_unattended_upgrades_site: "{{ apt_repo_uris | ansible.builtin.urlsplit('hostname') }}"

# apt-mark hold package
apt_mark_hold: false

# dotnet-sdk, moby-containerd, msopenjdk-21, mssql-tools, powershell
apt_repo_packages: []

# ansible_architecture return x86_64,
# but $(dpkg --print-architecture) returns "amd64"
dpkg_architectures:
  x86_64: amd64 # Common Intel/AMD 64-bit
  i386: i386 # Intel 32-bit
  i686: i386 # Older 32-bit
  aarch64: arm64 # 64-bit ARM
  armv7l: armhf # 32-bit ARM hard-float
  armv6l: armel # 32-bit ARM soft-float (rare)
  ppc64le: ppc64el # PowerPC 64-bit Little Endian
  s390x: s390x # IBM System z
  riscv64: riscv64 # RISC-V 64-bit
