---
- name: ensure gcloud_apt_key_signed_by directory exists
  ansible.builtin.file:
    path: "{{ gcloud_apt_key_signed_by | dirname }}"
    state: directory

- name: import apt key
  ansible.builtin.get_url:
    url: "{{ gcloud_apt_key }}"
    dest: "{{ gcloud_apt_key_signed_by }}"

- name: add apt repo
  ansible.builtin.apt_repository:
    repo: "{{ gcloud_apt_repo }}"
    filename: gcloud
    state: present

- name: add apt pinning
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/99gcloud
    content: |
      Package: *
      Pin: origin packages.cloud.google.com
      Pin-Priority: 900
    mode: "0644"

# 对于 371.0.0 之前的版本，该软件包名称为 google-cloud-sdk
- name: install gcloud packages
  ansible.builtin.apt:
    name:
      - google-cloud-cli
    update_cache: true
    state: present
