---
- name: set v2ray_asset_name
  ansible.builtin.set_fact:
    v2ray_asset_name: "v2ray-{{ ansible_system | lower }}-{{ v2ray_machine_dict[ansible_architecture] }}.zip"
  vars:
    # ref: https://github.com/v2fly/fhs-install-v2ray/blob/a9c7b8d4912b1fd184fdac908d3884972d8b0df7/install-release.sh#L62
    v2ray_machine_dict:
      i386: 32
      i686: 32
      amd64: 64
      x86_64: 64
      armv5tel: arm32-v5
      armv6l: arm32-v6
      armv7: arm32-v7a
      armv7l: arm32-v7a
      armv8: arm64-v8a
      aarch64: arm64-v8a
      mips: mips32
      mipsle: mips32le
      mips64: mips64
      mips64le: mips64le
      ppc64: ppc64
      ppc64le: ppc64le
      riscv64: riscv64
      s390x: s390x
  when:
    - not v2ray_asset_name
    - not v2ray_asset_url
  changed_when: false

- name: register v2ray_api_url_response
  ansible.builtin.uri:
    url: "{{ v2ray_api_url }}"
  register: v2ray_api_url_response
  when: not v2ray_asset_url
  changed_when: false

- name: json_query for browser_download_url
  ansible.builtin.set_fact:
    v2ray_asset_url: "{{ v2ray_api_url_response | community.general.json_query(query) | first }}"
  vars:
    query: "json.assets[?contains(browser_download_url, '{{ v2ray_asset_name }}')].browser_download_url"
  when: not v2ray_asset_url
  changed_when: false
