---
# nginx user
nginx_config_user: nginx
nginx_config_group: nginx

# configure whether to copy base nginx config
nginx_config_template_base_config: false

# configure whether to template a server.conf
nginx_config_template_server_config: true
