# https://cloud.google.com/sdk/docs/install?hl=zh-cn#deb
- name: apt_install - gcloud
  hosts: "{{ playbook_hosts | default('localhost') }}"
  become: true
  vars:
    # curl -sL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg
    # pub   rsa2048 2021-05-04 [SC]
    #       35BAA0B33E9EB396F59CA838C0BA5CE6DC6315A3
    # uid           Artifact Registry Repository Signer <artifact-registry-repository-signer@google.com>
    apt_keyrings_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    apt_keyrings_dest: /etc/apt/keyrings/gcloud.asc

    apt_repo: gcloud
    apt_repo_uris: https://packages.cloud.google.com/apt
    apt_repo_suites: cloud-sdk
    apt_repo_components: main

    apt_pinning: true
    apt_unattended_upgrade: true
    apt_mark_hold: false
    apt_pinning_pin_release: "o=cloud-sdk,n=cloud-sdk,c=main"
    apt_unattended_upgrade_origins_pattern: "origin=cloud-sdk,codename=cloud-sdk,component=main"

    apt_repo_packages:
      - google-cloud-cli

  tasks:
    - ansible.builtin.import_role:
        name: apt_install
