# https://packages.gitlab.com/gitlab/gitlab-ce/install#manual-deb
- name: apt_install - gitlab-ce
  hosts: "{{ playbook_hosts | default('localhost') }}"
  become: true
  vars:
    # curl -sL https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey | gpg
    # pub   rsa4096 2020-03-02 [SC] [expires: 2026-02-27]
    #       F6403F6544A38863DAA0B6E03F01618A51312F3F
    # uid           GitLab B.V. (package repository signing key) <packages@gitlab.com>
    # sub   rsa4096 2020-03-02 [E] [expires: 2026-02-27]
    apt_keyrings_url: https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
    apt_keyrings_dest: /etc/apt/keyrings/gitlab_gitlab-ce-archive-keyring.asc

    apt_repo: gitlab-ce
    apt_repo_uris:
      - "https://packages.gitlab.com/gitlab/gitlab-ce/{{ ansible_distribution | lower }}"
    apt_repo_suites:
      - "{{ ansible_distribution_release }}"
    apt_repo_components:
      - main

    apt_pinning: true
    apt_unattended_upgrade: true
    apt_mark_hold: false
    apt_pinning_pin_release: "o=packages.gitlab.com/gitlab/gitlab-ce,n={{ ansible_distribution_release }},c=main"
    apt_unattended_upgrade_origins_pattern: "origin=packages.gitlab.com/gitlab/gitlab-ce,codename={{ ansible_distribution_release }},component=main"

    apt_repo_packages:
      - gitlab-ce

  tasks:
    - ansible.builtin.import_role:
        name: apt_install
