# https://grafana.com/docs/grafana/latest/setup-grafana/installation/debian/
- name: apt_install - grafana
  hosts: "{{ playbook_hosts | default('localhost') }}"
  become: true
  vars:
    # curl -sL https://apt.grafana.com/gpg.key | gpg
    # pub   rsa3072 2023-08-24 [SC] [expires: 2025-08-23]
    #       B53AE77BADB630A683046005963FA27710458545
    # uid           Grafana Labs <engineering@grafana.com>
    # sub   rsa3072 2023-08-24 [E] [expires: 2025-08-23]
    apt_keyrings_url: https://apt.grafana.com/gpg.key
    apt_keyrings_dest: /etc/apt/keyrings/grafana.asc

    apt_repo: grafana
    apt_repo_uris: https://apt.grafana.com
    # stable / beta
    apt_repo_suites: stable
    apt_repo_components: main

    apt_pinning: true
    apt_unattended_upgrades: false
    apt_mark_hold: false

    # Grafana OSS: grafana
    # Grafana Enterprise: grafana-enterprise
    apt_repo_packages:
      - grafana

  tasks:
    - ansible.builtin.import_role:
        name: apt_install
