# https://www.hashicorp.com/en/official-packaging-guide
# The fingerprint must match 798A EC65 4E5C 1542 8C8E 42EE AA16 FCBC A621 E701, which can also be verified at https://www.hashicorp.com/security under "Linux Package Checksum Verification".
- name: apt_install - hashicorp
  hosts: "{{ playbook_hosts | default('localhost') }}"
  become: true
  vars:
    # curl -sL https://apt.releases.hashicorp.com/gpg | gpg
    # pub   rsa4096 2023-01-10 [SC] [expires: 2028-01-09]
    #       798AEC654E5C15428C8E42EEAA16FCBCA621E701
    # uid           HashiCorp Security (HashiCorp Package Signing) <security+packaging@hashicorp.com>
    # sub   rsa4096 2023-01-10 [S] [expires: 2028-01-09]
    apt_keyrings_url: https://apt.releases.hashicorp.com/gpg
    apt_keyrings_dest: /etc/apt/keyrings/hashicorp-archive-keyring.asc

    apt_repo: hashicorp
    apt_repo_uris:
      - https://apt.releases.hashicorp.com
    apt_repo_suites:
      - "{{ ansible_distribution_release }}"
    apt_repo_components:
      - main

    apt_pinning: true
    apt_unattended_upgrade: true
    apt_mark_hold: false

    # consul, packer, terraform, vagrant
    apt_repo_packages:
      - packer
      - terraform

  tasks:
    - ansible.builtin.import_role:
        name: apt_install
