# https://pkg.jenkins.io/debian/
- name: apt_install - jenkins
  hosts: "{{ playbook_hosts | default('localhost') }}"
  become: true
  vars:
    # curl -sL https://pkg.jenkins.io/debian/jenkins.io-2026.key | gpg
    # pub   rsa4096 2025-12-22 [SC] [expires: 2028-12-21]
    #       5E386EADB55F01504CAE8BCF7198F4B714ABFC68
    # uid           Jenkins Project <jenkinsci-board@googlegroups.com>
    apt_keyrings_url: https://pkg.jenkins.io/debian/jenkins.io-2026.key
    apt_keyrings_dest: /etc/apt/keyrings/jenkins.io-2026.asc

    apt_repo: jenkins-io
    apt_repo_uris:
      - https://pkg.jenkins.io/debian-stable
    # binary/ 后面这个斜杠居然不能去掉?
    apt_repo_suites:
      - binary/
    apt_repo_components:
      - ""

    apt_pinning: true
    apt_unattended_upgrade: true
    apt_mark_hold: false
    apt_pinning_pin_release: "o=jenkins.io,a=binary"
    apt_unattended_upgrade_origins_pattern: "origin=jenkins.io,suite=binary"

    apt_repo_packages:
      - fontconfig
      - openjdk-21-jre-headless
      - jenkins

  tasks:
    - ansible.builtin.import_role:
        name: apt_install
