# https://enterprise.proxmox.com/debian/
# https://pve.proxmox.com/wiki/Package_Repositories#sysadmin_no_subscription_repo
- name: apt_install - pve-no-subscription
  hosts: "{{ playbook_hosts | default('localhost') }}"
  become: true
  vars:
    # curl -sL https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg | gpg
    # pub   rsa4096 2022-11-27 [SC] [expires: 2032-11-24]
    #       F4E136C67CDCE41AE6DE6FC81140AF8F639E0C39
    # uid           Proxmox Bookworm Release Key <proxmox-release@proxmox.com>
    apt_keyrings_url: "https://enterprise.proxmox.com/debian/proxmox-release-{{ ansible_distribution_release }}.gpg"
    apt_keyrings_dest: "/etc/apt/keyrings/proxmox-release-{{ ansible_distribution_release }}.gpg"

    apt_repo: pve-no-subscription
    # proxmox 姑且在 https://enterprise.proxmox.com 下也提供了一份 GPG public key
    # 可以确保公钥来源可信, 那么 pve-no-subscription 刻意只提供 http 也可以保证 .deb 包的完整性
    apt_repo_uris: http://download.proxmox.com/debian/pve/
    apt_repo_suites: "{{ ansible_distribution_release }}"
    apt_repo_components: pve-no-subscription

    apt_pinning: true
    apt_unattended_upgrades: false
    apt_mark_hold: false

    apt_repo_packages: []

  tasks:
    - ansible.builtin.import_role:
        name: apt_install
