# https://github.com/smallstep/cli
# https://smallstep.com/docs/step-cli/installation/#debianubuntu
- name: apt_install - smallstep
  hosts: "{{ playbook_hosts | default('localhost') }}"
  become: true
  vars:
    # curl -sL https://packages.smallstep.com/keys/apt/repo-signing-key.gpg | gpg
    # pub   rsa2048 2021-05-04 [SC]
    #       35BAA0B33E9EB396F59CA838C0BA5CE6DC6315A3
    # uid           Artifact Registry Repository Signer <artifact-registry-repository-signer@google.com>
    apt_keyrings_url: https://packages.smallstep.com/keys/apt/repo-signing-key.gpg
    apt_keyrings_dest: /etc/apt/keyrings/smallstep.asc

    apt_repo: smallstep
    apt_repo_uris: https://packages.smallstep.com/stable/debian
    apt_repo_suites: debs
    apt_repo_components: main

    apt_pinning: true
    apt_unattended_upgrades: true
    apt_mark_hold: false

    apt_repo_packages:
      - step-cli

  tasks:
    - ansible.builtin.import_role:
        name: apt_install
