# https://code.visualstudio.com/docs/setup/linux
- name: apt_install - vscode
  hosts: "{{ playbook_hosts | default('localhost') }}"
  become: true
  vars:
    # https://packages.microsoft.com/keys/README
    # microsoft.asc (BC528686B50D79E339D3721CEB3E94ADBE1229CF):
    # This key was Microsoft's standard Linux-signing key until Spring 2025, as discussed above. This key will not be used for newly-created repositories.
    # microsoft-2025.asc (AA86F75E427A19DD33346403EE4D7792F748182B):
    # This is the current standard Linux-signing key that will be used in newly-created repositories. It will work properly in distributions that disallow SHA1 signatures.

    # vscode 应该算过去创建的 repository, 暂时听说会切换到 microsoft-2025.asc
    # curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg
    # pub   rsa2048 2015-10-28 [SC]
    #       BC528686B50D79E339D3721CEB3E94ADBE1229CF
    # uid           Microsoft (Release signing) <gpgsecurity@microsoft.com>
    # $ curl -sL https://packages.microsoft.com/keys/microsoft-2025.asc | gpg
    # pub   rsa4096 2023-11-15 [SC]
    #       AA86F75E427A19DD33346403EE4D7792F748182B
    # uid           Microsoft Corporation - General GPG Signer <gpgsign@microsoft.com>
    apt_keyrings_url: https://packages.microsoft.com/keys/microsoft.asc
    apt_keyrings_dest: /etc/apt/keyrings/microsoft.asc

    apt_repo: vscode
    apt_repo_uris:
      - https://packages.microsoft.com/repos/code
    apt_repo_suites:
      - stable
    apt_repo_components:
      - main

    apt_pinning: true
    apt_unattended_upgrade: true
    apt_mark_hold: false

    # code or code-insiders
    apt_repo_packages: []

  tasks:
    - ansible.builtin.import_role:
        name: apt_install
