---
- name: ensure docker_apt_key_signed_by directory exists
  ansible.builtin.file:
    path: "{{ docker_apt_key_signed_by }}"
    state: directory

- name: import apt key
  ansible.builtin.get_url:
    url: "{{ docker_apt_key }}"
    dest: "{{ docker_apt_key_signed_by }}/docker-ce.asc"

- name: add apt repo
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repo }}"
    filename: docker-ce
    state: present

- name: add apt pinning
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/99docker
    content: |
      Package: docker-*
      Pin: origin {{ docker_apt_repo_url | urlsplit('hostname') }}
      Pin-Priority: 900
    mode: "0644"

- name: install docker-ce packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      # https://docs.docker.com/engine/security/rootless/
      # require docker-ce version >= 20.10
      # - docker-ce-rootless-extras
      - skopeo
    state: present

- name: install docker-ce (x86_64 only) plugins
  ansible.builtin.apt:
    name:
      - docker-scan-plugin
    state: present
  when: ansible_architecture == 'x86_64'
