---
# tasks to apply changes
- include_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: add /etc/docker/daemon.json
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    force: true
  notify: restart dockerd

- name: register ansible regular user
  ansible.builtin.command:
    cmd: "awk -F: '$NF !~ /nologin|false/ && $3 >= 1000 {print $1}' /etc/passwd"
  register: ansible_regular_user
  changed_when: ansible_regular_user.rc != 0

- name: append 'docker' groups
  ansible.builtin.user:
    name: "{{ item }}"
    groups:
      - docker
    append: true
  loop: "{{ ansible_regular_user.stdout_lines }}"

- name: start and enable docker.service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
