---
# list: default DNS servers
default_nameservers:
  - 1.0.0.1#cloudflare-dns.com
  - 8.8.4.4#dns.google
# list: fallback DNS servers
fallback_nameservers: []
# - 1.1.1.1#cloudflare-dns.com
# - 8.8.8.8#dns.google

# bool: 是否使用 default_gateway 的地址覆盖 default_nameservers
# default_gateway 的地址为 透明代理 的地址时需要设置 tproxy_enabled 为 true
tproxy_enabled: false

# str: 默认网关
# 通过 netplan 在 ansible_facts['default_ipv4'].interface 上创建默认路由
default_gateway: ""

# str: systemd-resolved 的 /etc/resolv.conf 模式
# one of ["stub", "uplink", "static", "foreign"]
# stub: symlink to /run/systemd/resolve/stub-resolv.conf
# uplink: symlink to /run/systemd/resolve/resolv.conf
# static: symlink to /usr/lib/systemd/resolv.conf
# foreign: A plain text file not managed by systemd-resolved
systemd_resolved_resolv_conf_mode: "stub"

# bool: 是否创建全局 systemd-resolved 配置文件
# /etc/systemd/resolved.conf.d/90-override.conf
systemd_resolved_override: true
# bool: 此项为 true 意味着将设置 DNSOverTLS=yes
# systemd-resolved 现阶段只支持 DoT (DNS over TLS), 不支持 DoH (DNS over HTTPS)
# 注意: 中国大陆几乎无法使用任何由**国外**公共 DNS 提供的 DoT 和 DoH 如 Google DNS, Cloudflare DNS 等
systemd_resolved_dns_over_tls: false

# bool: 此项设置为 false 时用于禁用 cloud-init 的网络配置
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
# network: {config: disabled}
cloud_init_network_config: false

# bool: 此项设置为 false 用于避免修改 cloud-init drive 配置时被删除 `/etc/ssh/ssh_host_*` keys
# /etc/cloud/cloud.cfg.d/99-keep-sshd-host-keys.cfg
# ssh_deletekeys: false
cloud_init_ssh_deletekeys: false

# dict: 用于覆盖原本的 netmask prefix, 默认未空 dict
# 原因是网络中可能存在部分配置错误的 netmask
# 比如网络规划初期将单个 VLAN 配置为 172.16.0.0/12, 其 netmask 为 255.240.0.0, 对于小规模办公内网不太合理
interface_prefix_overrides: {}
# eth0: 16
# eth1: 22
