---
# ansible-playbook playbooks/certbot.yaml -e 'playbook_hosts=localhost' -e @credentials/certbot.yaml --ask-vault-pass
- name: install certbot
  hosts: "{{ playbook_hosts | default('localhost') }}"
  become: true

  tasks:
    - ansible.builtin.import_role:
        name: certbot
