---
- name: install certbot
  hosts: "{{ host | default('local') }}"
  vars:
    domain: ak1ra.xyz
    email: certbot@ak1ra.xyz
  roles:
    - role: certbot
      certbot_domain: "{{ domain }}"
      certbot_email: "{{ email }}"
