---
- name: install certbot
  hosts: "{{ playbook_hosts | default('localhost') }}"
  roles:
    - role: certbot
      certbot_domain: "{{ certbot_domain }}"
      certbot_email: "{{ certbot_email }}"
