---
- name: common tasks
  hosts: "{{ playbook_hosts | default('localhost') }}"
  become: true
  vars:
    apt_repo_debian_suites_backports_enabled: true

    unattended_upgrades_updates_enabled: true
    unattended_upgrades_automatic_reboot_enabled: true

    custom_sshd_config_enabled: false

  tasks:
    - ansible.builtin.import_role:
        name: common
