---
- name: install docker | unattended-upgrade
  hosts: "{{ playbook_hosts | default('localhost') }}"
  become: true
  vars:
    apt_repo_uris:
      - https://download.docker.com/linux/debian
      # - https://mirror-cdn.xtom.com/docker-ce/linux/debian
      # - https://mirrors.tencent.com/docker-ce/linux/debian
      # - https://mirrors.aliyun.com/docker-ce/linux/debian

    apt_pinning: true
    apt_unattended_upgrade: true
    apt_mark_hold: false

  tasks:
    - ansible.builtin.import_role:
        name: docker
