---
- name: install docker
  hosts: "{{ playbook_hosts | default('localhost') }}"
  become: true
  vars:
    apt_pinning: true
    apt_unattended_upgrade: false
    apt_mark_hold: false

  tasks:
    - ansible.builtin.import_role:
        name: docker
