---
- ansible.builtin.import_playbook: common.yaml

- ansible.builtin.import_playbook: certbot.yaml

- name: install nginx
  hosts: "{{ host | default('local') }}"
  vars:
    domain: ak1ra.xyz
  roles:
    - role: nginx
      nginx_apt_repo: debian

    - role: nginx_config
      nginx_config_template_base_config: true
      nginx_config_template_server_config: true
      nginx_config_domain: "{{ domain }}"
      nginx_config_server_name: "{{ domain }}"
      nginx_config_server_type: static
